import AuthGuard from "@/providers/authGuard";
import "./globals.css";
import StoreProviders from "@/providers/storeProvider";
import { Metadata } from "next";
import RefetchDataProviders from "@/providers/refetchData";
import { I18nProvider } from "@/providers/I18nProvider";
import { AppWithSocket } from "@/providers/ApiWithSocket";

export const metadata: Metadata = {
  title: "DocGen",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-warning.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen flex flex-col justify-between"
        cz-shortcut-listen="true"
      >
        <StoreProviders>
          <AuthGuard>
            <RefetchDataProviders>
              <I18nProvider>
                <AppWithSocket>{children}</AppWithSocket>
              </I18nProvider>
            </RefetchDataProviders>
          </AuthGuard>
        </StoreProviders>
      </body>
    </html>
  );
}