import AuthGuard from "@/providers/authGuard";
import "./globals.css";
import StoreProviders from "@/providers/storeProvider";
import { Metadata } from "next";
import RefetchDataProviders from "@/providers/refetchData";

export const metadata: Metadata = {
  title: "DocGen",
  description: "Generated by create next app",
  icons:{
    icon: "/logo-warning.png"
  }
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body 
        className="min-h-screen flex flex-col justify-between"
        cz-shortcut-listen="true"
      >
        <StoreProviders>
          <AuthGuard>
            <RefetchDataProviders>
              {children}
            </RefetchDataProviders>
          </AuthGuard>
        </StoreProviders>
      </body>
    </html>
  );
}
